<a href="https://colab.research.google.com/github/panditrahulsharma/python-programming/blob/master/bank_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
import os
os.getcwd()

'/content'

In [0]:
os.chdir('/content/drive/My Drive/deep-learning/day27')


In [0]:
import pandas as pd
dataset = pd.read_csv("Churn_Modelling.csv")


In [19]:
features.shape


(10000, 11)

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

features = dataset.iloc[:, 3:13].values
labels = dataset.iloc[:, 13].values


In [14]:
features


array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [15]:
labels

array([1, 0, 1, ..., 1, 1, 0])

In [16]:

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_features_1 = LabelEncoder()
features[:, 1] = labelencoder_features_1.fit_transform(features[:, 1])

labelencoder_features_2 = LabelEncoder()
features[:, 2] = labelencoder_features_2.fit_transform(features[:, 2])

onehotencoder = OneHotEncoder(categorical_features = [1])
features = onehotencoder.fit_transform(features).toarray()

features = features[:, 1:] #dummy variable trap


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [0]:

from sklearn.model_selection import train_test_split
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size = 0.2, random_state = 0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
features_train = sc.fit_transform(features_train)
features_test = sc.transform(features_test)

In [21]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [24]:
classifier = Sequential()

features.shape

#adding the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(features_train, labels_train, batch_size = 10, epochs = 10)

labels_pred = classifier.predict(features_test)
labels_pred = (labels_pred > 0.5)

len(labels_pred)

Epoch 1/10
8000/8000 [==============================] - 1s 176us/step - loss: 0.4882 - acc: 0.7955
Epoch 2/10
8000/8000 [==============================] - 1s 120us/step - loss: 0.4272 - acc: 0.7960
Epoch 3/10
8000/8000 [==============================] - 1s 117us/step - loss: 0.4217 - acc: 0.7960
Epoch 4/10
8000/8000 [==============================] - 1s 113us/step - loss: 0.4179 - acc: 0.8195
Epoch 5/10
8000/8000 [==============================] - 1s 115us/step - loss: 0.4158 - acc: 0.8286
Epoch 6/10
8000/8000 [==============================] - 1s 112us/step - loss: 0.4136 - acc: 0.8292
Epoch 7/10
8000/8000 [==============================] - 1s 114us/step - loss: 0.4126 - acc: 0.8306
Epoch 8/10
8000/8000 [==============================] - 1s 117us/step - loss: 0.4113 - acc: 0.8319
Epoch 9/10
8000/8000 [==============================] - 1s 116us/step - loss: 0.4103 - acc: 0.8325
Epoch 10/10
8000/8000 [==============================] - 1s 114us/step - loss: 0.4093 - acc: 0.8337


2000

In [38]:
labels_pred = classifier.predict(features_test)
labels_pred = (labels_pred > 0.5)
#this label_pred gives result in percent that convert into 1,0 using condition

len(labels_pred)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(labels_test, labels_pred)

cm

array([[1557,   38],
       [ 284,  121]])